/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Models for OpenAI-compatible API requests and responses.
 */

/**
 * Request body for OpenAI-compatible chat completions API
 */
export interface OpenAIChatCompletionRequest {
  /**
   * ID of the model to use
   */
  model: string;

  /**
   * A list of messages comprising the conversation so far
   */
  messages: OpenAIMessage[];

  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far,
   * decreasing the model's likelihood to repeat the same line verbatim.
   */
  frequency_penalty?: number;

  /**
   * Modify the likelihood of specified tokens appearing in the completion.
   */
  logit_bias?: Record<string, number>;

  /**
   * Whether to return log probabilities of the output tokens or not.
   */
  logprobs?: boolean;

  /**
   * The maximum number of tokens to generate in the chat completion.
   */
  max_tokens?: number;

  /**
   * How many chat completion choices to generate for each input message.
   */
  n?: number;

  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far,
   * increasing the model's likelihood to talk about new topics.
   */
  presence_penalty?: number;

  /**
   * An object specifying the format that the model must output.
   */
  response_format?: { type: 'text' | 'json_object' };

  /**
   * This feature is in Beta. If specified, our system will make a best effort to sample deterministically,
   * such that repeated requests with the same seed and parameters should return the same result.
   */
  seed?: number;

  /**
   * Up to 4 sequences where the API will stop generating further tokens.
   */
  stop?: string | null | string[];

  /**
   * If set, partial message deltas will be sent, like in ChatGPT.
   */
  stream?: boolean;

  /**
   * What sampling temperature to use, between 0 and 2.
   */
  temperature?: number;

  /**
   * An alternative to sampling with temperature, called nucleus sampling.
   */
  top_p?: number;

  /**
   * A unique identifier representing your end-user.
   */
  user?: string;
}

/**
 * Message object for OpenAI-compatible API
 */
export interface OpenAIMessage {
  /**
   * The role of the message author. One of "system", "user", or "assistant".
   */
  role: 'system' | 'user' | 'assistant';

  /**
   * The content of the message.
   */
  content: string;
}

/**
 * Response from OpenAI-compatible chat completions API
 */
export interface OpenAIChatCompletionResponse {
  /**
   * A unique identifier for the chat completion.
   */
  id: string;

  /**
   * A list of chat completion choices.
   */
  choices: OpenAIChatCompletionChoice[];

  /**
   * The model used for the chat completion.
   */
  model: string;

  /**
   * The Unix timestamp (in seconds) of when the chat completion was created.
   */
  created: number;

  /**
   * The object type, which is always "chat.completion".
   */
  object: string;

  /**
   * Usage information for the request.
   */
  usage?: OpenAIUsage;
}

/**
 * Choice object in OpenAI-compatible chat completion response
 */
export interface OpenAIChatCompletionChoice {
  /**
   * A chat completion delta generated by streamed model responses.
   */
  message: OpenAIMessage;

  /**
   * The reason the model stopped generating tokens.
   */
  finish_reason: string;

  /**
   * The index of the choice in the list of choices.
   */
  index: number;
}

/**
 * Usage information for OpenAI-compatible API response
 */
export interface OpenAIUsage {
  /**
   * Number of tokens in the prompt.
   */
  prompt_tokens: number;

  /**
   * Number of tokens in the generated completion.
   */
  completion_tokens: number;

  /**
   * Total number of tokens used in the request (prompt + completion).
   */
  total_tokens: number;
}

/**
 * Request body for OpenAI-compatible completions API
 */
export interface OpenAICompletionRequest {
  /**
   * ID of the model to use
   */
  model: string;

  /**
   * The prompt(s) to generate completions for, encoded as a string, array of strings, array of tokens, or array of token arrays.
   */
  prompt: string | string[];

  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far.
   */
  frequency_penalty?: number;

  /**
   * Modify the likelihood of specified tokens appearing in the completion.
   */
  logit_bias?: Record<string, number>;

  /**
   * Whether to return log probabilities of the output tokens or not.
   */
  logprobs?: number;

  /**
   * The maximum number of tokens to generate in the completion.
   */
  max_tokens?: number;

  /**
   * How many completions to generate for each prompt.
   */
  n?: number;

  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far.
   */
  presence_penalty?: number;

  /**
   * Up to 4 sequences where the API will stop generating further tokens.
   */
  stop?: string | null | string[];

  /**
   * If set, partial message deltas will be sent, like in ChatGPT.
   */
  stream?: boolean;

  /**
   * What sampling temperature to use, between 0 and 2.
   */
  temperature?: number;

  /**
   * An alternative to sampling with temperature, called nucleus sampling.
   */
  top_p?: number;

  /**
   * A unique identifier representing your end-user.
   */
  user?: string;

  /**
   * The suffix that comes after a completion of inserted text.
   */
  suffix?: string;
}

/**
 * Response from OpenAI-compatible completions API
 */
export interface OpenAICompletionResponse {
  /**
   * A unique identifier for the completion.
   */
  id: string;

  /**
   * A list of completion choices.
   */
  choices: OpenAICompletionChoice[];

  /**
   * The model used for the completion.
   */
  model: string;

  /**
   * The Unix timestamp (in seconds) of when the completion was created.
   */
  created: number;

  /**
   * The object type, which is always "text_completion".
   */
  object: string;

  /**
   * Usage information for the request.
   */
  usage?: OpenAIUsage;
}

/**
 * Choice object in OpenAI-compatible completion response
 */
export interface OpenAICompletionChoice {
  /**
   * The generated text completion.
   */
  text: string;

  /**
   * The reason the model stopped generating tokens.
   */
  finish_reason: string;

  /**
   * The index of the choice in the list of choices.
   */
  index: number;

  /**
   * Log probabilities for the output tokens.
   */
  logprobs?: unknown;
}
